input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["service.logs"]
    group_id => "logstash-consumer"
    codec => json
    decorate_events => "basic"
  }
}

filter {
  if [level] {
    mutate {
      lowercase => ["level"]
    }
  }

  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }

  if [trace_id] {
    mutate {
      add_field => { "[@metadata][trace_id]" => "%{trace_id}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
}
